name: Java CI Test Ubuntu Sonar

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build on ubuntu
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Build with Maven and SonarCloud
      run: >
        xvfb-run mvn -B verify -Pjacoco -DskipE2E sonar:sonar
        -Dsonar.projectKey=marcodiri_java_socketio_chatroom
        -Dsonar.organization=marcodiri
        -Dsonar.host.url=https://sonarcloud.io
      working-directory: java_socketio_chatroom_aggregator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
